### ISSUE TITLE
stat() errors

### ISSUE THREAD

**Issue by darxmac** [php-vcr/php-vcr#205]
I'm trying to use php-cvr in a CakePHP plugin, but it fails when the FileCache engine tries to check if a cache file exists or not, and when it does not, stat() fails like this:

```
1) Shop\Test\TestCase\Controller\PaymentsControllerTest::testStripeErrors
RuntimeException: stat(): stat failed for /var/folders/4m/9gjjdkm95_90s3jpbrm0q33h0000gn/T/caketest/cake_translations_cake_en__u_s__p_o_s_i_x in /projectvendor/php-vcr/php-vcr/src/VCR/Util/StreamProcessor.php:307
Stack trace:
#0 /projectvendor/php-vcr/php-vcr/src/VCR/Util/StreamProcessor.php(307): stat('/var/folders/4m...')
#1 [internal function]: VCR\Util\StreamProcessor->url_stat('/var/folders/4m...', 2)
#2 /projectvendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php(388): SplFileInfo->isFile()
#3 /projectvendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php(184): Cake\Cache\Engine\FileEngine->_setKey('cake_translatio...')
#4 /projectvendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(148): Cake\Cache\Engine\FileEngine->read('cake_translatio...')
```

any ideas ?

When running the tests with the cache file in place, it works fine

**Comment by snelg** [comment]
Ran into this myself. Tracked down the root problem and submitted pull request #231 to fix the issue.

**Comment by higidi** [comment]
Closing — fixed on master.

`StreamProcessor::url_stat()` now checks `STREAM_URL_STAT_QUIET` before calling `stat()`, and uses `@stat()` with suppressed errors when the flag is set. The `RuntimeException` thrown on a missing cache file no longer occurs.

Fix was introduced via PR #231.
